In [1]:
from __future__ import print_function
import keras
import random, os
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D, Dropout, Flatten
from keras.models import Model, Sequential
from keras import backend as K
from glob import glob
from PIL import Image
import numpy as np
import re

batch_size = 128
num_classes = 6
epochs = 12

Using TensorFlow backend.


In [2]:
img_rows, img_cols = 28, 28
label = ["circle", "square", "triangle", "horizontal", "vertical", "diagonal"]

In [3]:
def load_data():
    path = 'trains/'
    dataset = []
    filenames = os.listdir(path)
    index = 0
    labels = []
    for file in filenames:
        pic = Image.open(path + file)
        lb = file.replace(re.findall("\d+", file)[0], '').replace('.png', '')
        labels.append(label.index(lb))
        pic = np.array(pic)
        dataset.append(pic)
    dataset = np.array(dataset)
    labels = np.array(labels)
    return dataset, labels

(x_train, y_train) = load_data()
y_train = keras.utils.to_categorical(y_train, num_classes)
input_shape = (img_rows, img_cols, 1)

In [4]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_train = x_train.astype('float32')
x_train /= 255

print(x_train.shape, y_train.shape)
print(input_shape, y_train)
print('x_train shape:', x_train.shape)
#print(x_train.shape[0], 'train samples')

(900, 28, 28, 1) (900, 6)
(28, 28, 1) [[0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 ...
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]]
x_train shape: (900, 28, 28, 1)


In [5]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [6]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

In [7]:
print(x_train.shape)

(900, 28, 28, 1)


In [8]:
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1)

Epoch 1/12
900/900 [==============================] - 1s 2ms/step - loss: 1.8215 - acc: 0.1633
Epoch 2/12
900/900 [==============================] - 0s 42us/step - loss: 1.7788 - acc: 0.1844
Epoch 3/12
900/900 [==============================] - 0s 41us/step - loss: 1.7625 - acc: 0.2144
Epoch 4/12
900/900 [==============================] - 0s 45us/step - loss: 1.7068 - acc: 0.2756
Epoch 5/12
900/900 [==============================] - 0s 47us/step - loss: 1.6667 - acc: 0.2844
Epoch 6/12
900/900 [==============================] - 0s 46us/step - loss: 2.0455 - acc: 0.3011
Epoch 7/12
900/900 [==============================] - 0s 45us/step - loss: 1.5662 - acc: 0.3056
Epoch 8/12
900/900 [==============================] - 0s 47us/step - loss: 1.5044 - acc: 0.3367
Epoch 9/12
900/900 [==============================] - 0s 45us/step - loss: 1.4630 - acc: 0.3567
Epoch 10/12
900/900 [==============================] - 0s 48us/step - loss: 1.4559 - acc: 0.3678
Epoch 11/12
900/900 [===================